### PR TITLE
Switch search api workers to use new redis instance in production

### PR DESCRIPTION
**Pull request by callumknights**
Trello: https://trello.com/c/znEDt0yK/1364-create-new-redis-instance-for-search-api-and-move-search-api-to-it-peri-peri-%F0%9F%8C%B6%EF%B8%8F

### CODE REVIEW

**Review by theseanything — CHANGES_REQUESTED** [review]
We need to specify the new requests as per integration - https://github.com/alphagov/govuk-helm-charts/pull/2570

**Comment by theseanything** [comment]
Addressed here: https://github.com/alphagov/govuk-helm-charts/pull/2571

**Review by theseanything — APPROVED** [review]

**Comment by theseanything** [comment]
Sorry, should have made that more clear - I've addressed it in https://github.com/alphagov/govuk-helm-charts/pull/2571

But that PR needs to be merged before this one.

**Comment by callumknights** [comment]
Ah I get you. Luckily I'm working on something else anyway, so I'll hold off on this till that's merged. 👍

**Pull request merged**
