### PR TITLE
Add Google site verification to nginx

### PR DESCRIPTION
**Pull request by marcpomfret**
Removed config from asset-manager nginx and added to static only for all envs, tested and working in integration

### CODE REVIEW

**Review by sengi — COMMENTED** [review]
Which domain does this need to be served on?

**Comment by theseanything** [comment]
@marcpomfret is this going to enable to verification for all domains? I think it's only needed for the asset domain? i.e. https://www.gov.uk/googlec908b3bc32386239.html doesn't work

**Comment by sengi** [comment]
If it's for the assets domain then it'll be the [asset-manager nginx config](https://github.com/alphagov/govuk-helm-charts/blob/main/charts/asset-manager/templates/nginx-configmap.yaml) that you want.

**Comment by sengi** [comment]
Oh, sorry for the bad steer there. It is indeed going to static.

**Comment by sengi** [comment]
I don't think it's going via Router, though. At least not the way we've got it set up at the moment.

**Comment by sengi** [comment]
It's a little tricky to see from the config but static has an ingress that's sharing an ALB with asset-manager (and whitehall-frontend). The catch-all path goes to static, so I think this request will be going from assets-origin ALB straight to the static Service.

**Comment by marcpomfret** [comment]
yeah got it, added an extra bit to static and the = in the other config, tested it out works now

**Review by sengi — APPROVED** [review]

**Pull request merged**
