### PR TITLE
Enable ELB logging to S3 for router's load balancer in all environments

### PR DESCRIPTION
**Pull request by samsimpson1**
https://trello.com/c/aHggiTgs/1009-enable-alb-logging-to-s3

### CODE REVIEW

**Review by nsabri1 — COMMENTED** [review]
I wonder if this is only needed in Production

**Comment by samsimpson1** [comment]
@nsabri1 it's enabled in all environments for the LBs for the EC2-based system, and it won't incur much cost since the logs are deleted after a few days in each environment. We may as well have them available in case they're needed

**Comment by sengi** [comment]
Yeah I'd recommend keeping logs in all three environments but just having shorter retention on integration and staging.

**Comment by nsabri1** [comment]
> Member

Ok thats answered my question. will approve thanks for this

**Review by nsabri1 — APPROVED** [review]

**Comment by samsimpson1** [comment]
The bucket specified is actually the same one used for the old load balancers. I didn't see the need to create a new one when we could use the one already there. We will need to move it into the new terraform after we decommission the old environments, however.

**Pull request merged**
