### PR TITLE
Comment out queue worker for Chat

### PR DESCRIPTION
**Pull request by kevindew**
This is to stop this process as it seems to be caught in an infinite error loop and I'm not sure of a better way to stop the process.

### CODE REVIEW

**Review by peteglondon — APPROVED** [review]

**Review by sengi — APPROVED** [review]

**Review by sengi — COMMENTED** [review]
You could alternatively set workerReplicas: 0 but either is fine.

**Comment by kevindew** [comment]
> You could alternatively set workerReplicas: 0 but either is fine.

Thanks for the tip, is this something that is always done through helm charts? I was trying to work out if I could do it via the Argo UI.

**Comment by sengi** [comment]
Yes — Git should be authoritative for pretty much all GOV.UK's configuration these days, at least that's [the theory](https://www.redhat.com/en/topics/devops/what-is-gitops#what-is-gitops)!

**Comment by kevindew** [comment]
Super, makes a lot of sense.

Final question, as we wanted to just kill one of the worker processes and not both. I imagine that can't be done with `workerReplicas: 0` as that'd stop both right?

**Comment by sengi** [comment]
Oh, in that case you could simply delete the pod.

**Pull request merged**
