### PR TITLE
Add shield advanced protection to EKS ALBs

### PR DESCRIPTION
**Pull request by sihugh**
We had this enabled on the load balancers for our EC2 instances, and it's worth bringing across. There's a few benefits, including proactive engagement from the AWS SRT team and better monitoring options in CloudWatch.

We already pay for the subscription as part of the org, so it's free to us at this point.

### CODE REVIEW

**Review by sengi — APPROVED** [review]
Oh wow, none of us had clocked that this requires opt-in for each individual load balancer! Good catch, thanks!

**Comment by sengi** [comment]
We can (and probably should) use a [Firewall Manager policy](https://docs.aws.amazon.com/waf/latest/developerguide/shield-policies.html) to configure these account-wide instead of doing it per-LB, so that we have a single point of control and don't need to rely on adding that annotation everywhere in future.

**Comment by theseanything** [comment]
@sihugh let us know if you need any help getting this in

**Comment by sengi** [comment]
I totally missed that it was just a (data)type issue, not anything fancy with the schemas.

**Comment by sengi** [comment]
Thanks for the PR! 🙇

**Pull request merged**
