### PR TITLE
Add email-alert-api tokens for content-data-admin in  staging/production

### PR DESCRIPTION
**Pull request by KludgeKML**
Values added for integration earlier, add them for other environments.

https://trello.com/c/xng5X4uX/30-add-email-statistics-into-content-data-admin

### CODE REVIEW

**Review by peteglondon — APPROVED** [review]

**Review by sengi — APPROVED** [review]
fyi
```
k get secret signon-token-content-data-admin-email-alert-api
... "signon-token-content-data-admin-email-alert-api" not found
```

**Comment by KludgeKML** [comment]
@sengi Ah yeah, the tokens have only just been made in production, so I don't think the job has run to copy them. But they won't be needed until tomorrow (at which point it'll also have been copied to Staging I assume?) . I think that's okay, unless I've misunderstood something?

**Comment by sengi** [comment]
It's fine, but your rollout will just be stuck until the cronjob runs and creates the missing secrets.

**Comment by sengi** [comment]
You can run [the cronjob](https://argo.eks.production.govuk.digital/applications/signon?orphaned=false&resource=&node=batch%2FCronJob%2Fapps%2Fsignon-sync-token-secrets-to-k8s%2F0) sooner to make the crashloopy pods go away and let the rollout finish, if you like (three-vertical-dots menu -> create job)

**Comment by KludgeKML** [comment]
Ah, I didn't realise that would block the rollout. Thanks! Done.

**Pull request merged**
