### PR TITLE
Permit access to Frontend for draft CSV previews in integration

### PR DESCRIPTION
**Pull request by brucebolt**
This adds ingress to Frontend at the draft asset host for CSV previews and the assets needed to render the page.

[Trello card](https://trello.com/c/a67EW0uB)

### CODE REVIEW

**Review by sengi — APPROVED** [review]

**Comment by sengi** [comment]
Controller doesn't look happy this time :(

`k -n cluster-services logs deploy/aws-load-balancer-controller | grep assets-origin`

```json
{
  "level": "error",
  "ts": 1687266587.2025476,
  "logger": "controller-runtime.manager.controller.ingress",
  "msg": "Reconciler error",
  "name": "assets-origin",
  "namespace": "",
  "error": "ingress: apps/frontend: prefix path shouldn't contain wildcards: /government/uploads/system/uploads/attachment_data/file/*/*/preview"
}
```

**Comment by brucebolt** [comment]
Yeah, just looking at this in Argo's event log.

I've missed off `pathType: ImplementationSpecific` compared to the other containing wildcards.  I can't see any mention of wildcards in the docs, but maybe this is what I need toadd?

**Comment by sengi** [comment]
Ah snap, was just about to post this :) Yeah adding `pathType: ImplementationSpecific` should fix it.

**Comment by brucebolt** [comment]
Thanks @sengi.  Have raised https://github.com/alphagov/govuk-helm-charts/pull/1172 to fix this.

**Comment by sengi** [comment]
Yeah I can see how it'd be a tricky one to find out about. The wildcard pattern matching isn't a feature of aws-lb-controller, nor a feature of Ingress. It's a [feature of the ELBv2 API](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions).

**Comment by brucebolt** [comment]
Ah, that makes sense.  I was starting to wonder if it was something custom that we'd written, but this explains why adding that `pathType` works here.

**Pull request merged**
